//
//  PaintThreeColorGradient.h
//  PaintThreeColorGradient
//
//  Created by Jubal on 16/2/1.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PaintThreeColorGradient : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* paintThreeColorGradientTargets;

// Colors
+ (UIColor*)leftMainColor;
+ (UIColor*)topColor;
+ (UIColor*)downColor;
+ (UIColor*)rightMainColor;
+ (void)setLeftMainColor:(UIColor*)leftMainColor;
+ (void)setRightMainColor:(UIColor*)rightMainColor;
+ (void)setTopColor:(UIColor*)topColor;
+ (void)setDownColor:(UIColor*)downColor;

// Drawing Methods
+ (void)drawPaintThreeColorGradient;

// Generated Images
+ (UIImage*)imageOfPaintThreeColorGradient;

@end
